# Generated by Django 5.0.1 on 2024-01-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='host',
            field=models.CharField(default='lol', max_length=50),
        ),
    ]
