# Generated by Django 5.0.1 on 2024-01-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='host',
            new_name='session_host',
        ),
    ]
