# Generated by Django 5.0.1 on 2024-01-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_host_image_session_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='session_host',
            new_name='host',
        ),
    ]
