# Generated by Django 5.0.1 on 2024-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_image_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.CharField(default='256x256', max_length=9),
        ),
    ]
