# Generated by Django 5.0.1 on 2024-01-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_image_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='generated_image',
        ),
        migrations.AddField(
            model_name='image',
            name='generated_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_prompt',
            field=models.TextField(default=''),
        ),
    ]
