# Generated by Django 5.0.1 on 2024-01-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_image_generated_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='generated_image_url',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_prompt',
            field=models.CharField(max_length=200),
        ),
    ]
