# Generated by Django 5.0.1 on 2024-01-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_image_generated_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='generated_image_url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='text_prompt',
            field=models.CharField(max_length=255),
        ),
    ]
