# Generated by Django 5.0.1 on 2024-01-31 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_image_generated_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='generated_image_url',
            field=models.TextField(),
        ),
    ]
