# Generated by Django 5.0.1 on 2024-01-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_image_generated_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='text_prompt',
            field=models.TextField(max_length=1000),
        ),
    ]
